---
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:

    freeipa:
      hosts:
        ipa01.lab.internal:
          ansible_host: 192.168.10.5

    k8s_cluster:
      children:
        control_plane:
          hosts:
            k8s-cp01.lab.internal:
              ansible_host: 192.168.10.10
              rke2_type: server

        workers:
          hosts:
            k8s-w01.lab.internal:
              ansible_host: 192.168.10.11
              rke2_type: agent
              node_labels:
                - "node-role=devops"

            k8s-w02.lab.internal:
              ansible_host: 192.168.10.12
              rke2_type: agent
              node_labels:
                - "node-role=monitoring"

            k8s-w03.lab.internal:
              ansible_host: 192.168.10.13
              rke2_type: agent
              node_labels:
                - "node-role=netops"

    k8s_nodes:
      children:
        control_plane:
        workers:
