---
# roles/common/handlers/main.yml

- name: reboot if kernel updated
  reboot:
    reboot_timeout: 300
    msg: "Rebooting after kernel upgrade"
  when: dnf_upgrade.changed

- name: restart chrony
  service:
    name: chronyd
    state: restarted
