---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: freeipa-ca-issuer
spec:
  ca:
    secretName: freeipa-ca-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
