replicaCount: 2

config:
  splunk:
    host: "https://10.0.10.117:8088/services/collector/event"
    token: "ecb425db-bc7e-416c-ba00-0acc5e6d9d71"
    index: "falco_alerts"
    sourcetype: "falco"
    minimumpriority: "notice"
    checkcert: false

  customfields:
    environment: "homelab-k8s"
    cluster: "rke2-us-west-2"
    compliance_framework: "CMMC_L2"

  stdout:
    enabled: true
    minimumpriority: "debug"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
