---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media
  namespace: netops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
