defaultSettings:
  defaultReplicaCount: 2
  storageMinimalAvailablePercentage: 10
  defaultDataPath: /var/lib/longhorn
  backupTarget: ""
  autoSalvage: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  defaultFsType: ext4

ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.lab.internal
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-realm: "Longhorn"

longhornUI:
  replicas: 1
