# Syslog inputs for Splunk Universal Forwarder
# Monitors system logs on each K8s node

[monitor:///var/log/messages]
index = os_logs
sourcetype = linux_messages_syslog

[monitor:///var/log/secure]
index = os_logs
sourcetype = linux_secure

[monitor:///var/log/audit/audit.log]
index = os_logs
sourcetype = linux_audit
