---
# Splunk License Secret
# Place your Splunk Enterprise or free trial license file content here.
# Seal with kubeseal before committing.
#
# For free/developer license: omit this secret — Splunk starts in free mode (500MB/day)
# For full license:
#   kubectl create secret generic splunk-licenses \
#     --from-file=license=/path/to/splunk.lic \
#     --namespace logging
apiVersion: v1
kind: Secret
metadata:
  name: splunk-licenses
  namespace: logging
type: Opaque
data:
  license: ""  # Base64-encoded .lic file content
