---
apiVersion: v1
kind: Endpoints
metadata:
  name: freeipa
  namespace: auth
subsets:
  - addresses:
      - ip: 10.0.10.113
    ports:
      - name: ldap
        port: 389
        protocol: TCP
      - name: ldaps
        port: 636
        protocol: TCP
